name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupérer le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurer la connexion SSH
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 3. Déployer le projet sur le VPS
    - name: Deploy Project to VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@194.164.72.129 << 'EOF'
          set -e
          apt update && apt install -y curl
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt install -y nodejs
          npm install -g pm2

          # Nettoyer l'ancien projet et déployer le nouveau
          rm -rf /var/www/nextjs-app
          mkdir -p /var/www/nextjs-app
        EOF

        # Utiliser rsync pour synchroniser les fichiers de manière sécurisée
        rsync -avz --exclude='.git' --exclude='node_modules' ./ root@194.164.72.129:/var/www/nextjs-app/

    # 4. Transférer les variables d'environnement (.env)
    - name: Transfer Environment Variables
      run: |
        echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" > .env
        echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
        echo "EMAIL_RECIPIENT=${{ secrets.EMAIL_RECIPIENT }}" >> .env

        rsync -avz .env root@194.164.72.129:/var/www/nextjs-app/.env

    # 5. Installer les dépendances et démarrer l'application avec PM2
    - name: Install Dependencies and Start App
      run: |
        ssh -o StrictHostKeyChecking=no root@194.164.72.129 << 'EOF'
          set -e
          cd /var/www/nextjs-app
          npm ci
          npm run build

          # Démarrer ou recharger proprement avec PM2
          pm2 startOrReload ecosystem.config.js --env production || pm2 start npm --name "nextjs-app" -- start
          pm2 save
        EOF
